version: '3'

services:
  embulk:
    build: .
    image: himaoka/embulk:0.9.16
    volumes:
      - .:/src
    working_dir: /src
    command: tail -f /dev/null
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
