version: '3'

services:
  embulk:
    image: himaoka/embulk:0.3
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_DEFAULT_REGION
      - AWS_PROFILE
    volumes:
      - .:/src
      - ~/.aws:/root/.aws
    working_dir: /src
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
